# Datasource Properties
spring.datasource.host              = 127.0.0.1
spring.datasource.post              = 3306
spring.datasource.client            = jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}
spring.datasource.database          = community_ecommerce_db
spring.datasource.url               = ${spring.datasource.client}/${spring.datasource.url}
spring.datasource.username          = wulf
spring.datasource.password          = wulf123
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Mongo Properties
spring.data.mongodb.host     = 127.0.0.1
spring.data.mongodb.port     = 27017
spring.data.mongodb.client   = mongodb://127.0.0.1:27017
spring.data.mongodb.database = bloggerDB
spring.data.mongodb.url      = mongodb://127.0.0.1:27017/bloggerDB
spring.data.mongodb.username = wulf
spring.data.mongodb.password = wulf123